export const states = {
    HOME: '/home',
    HELP: '/help',
    ABOUT: '/about',
    AVAIL: '/avail',
    NEW: '/new_order',
    PHONE_PARTNER: 'PHONE_PARTNER',
    DELIV_TYPE: 'DELIV_TYPE',
    PHOTO_PAYM: 'PHOTO_PAYM',
    NP_METHOD: 'NP_METHOD',
    TYPE_NP: 'новая почта',
    TYPE_UP: 'укрпошта',
    TYPE_OTHER: 'прочее',
    CLIENT_NAME: 'NAME_CLIENT',
    CLIENT_PHONE: 'PHONE_CLIENT',
    NP_DELIV: 'NP_DELIV',
    NP_CITY: 'NP_CITY',
    NP_WH: 'NP_WH',
    NP_STREET: 'NP_STREET',
    NP_HOUSE: 'NP_HOUSE',
    NP_FLAT: 'NP_FLAT',
    UP_INDEX: 'UP_INDEX',
    ITEM: 'ITEM',
    SIZE: 'SIZE',
    QTY: 'QTY',
    SEND: 'SEND',
    CREATED: 'CREATED'
}
